version: '2'
services:
  database_slave:
    image: mysql:5.7
    container_name: database_slave
    volumes:
      - ./docker/database/dumps/slave:/dumps:rw,cached
      - ./docker/database/data/mysql-slave:/var/lib/mysql:rw,cached
      - ./docker/database/config/mysql-slave:/etc/mysql/conf.d:rw,cached
      - ./docker/database/log/mysql-slave:/var/log/mysql:rw,cached
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3307:3306"
    restart: always

  mysql_configure:
    image: mysql:5.7
    environment:
      - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASSWORD}
      - MYSQL_MASTER_ADDRESS=${MYSQL_MASTER_ADDRESS}
      - MYSQL_MASTER_PORT=${MYSQL_MASTER_PORT}

      - MYSQL_SLAVE_ADDRESS=${MYSQL_SLAVE_ADDRESS}
      - MYSQL_SLAVE_PORT=${MYSQL_SLAVE_PORT}
      - MYSQL_SLAVE_ROOT_PASSWORD=${MYSQL_SLAVE_ROOT_PASSWORD}

      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - ./docker/database/config/mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
